name: Check spelling

on:
  # No intention of pull requests, so don't setup the action to run on
  # pull requests.
  push:
    branches: main

jobs:
  spell-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: streetsidesoftware/cspell-action@v6
